# Generated by Django 4.2.2 on 2023-06-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fiel_of_study',
            new_name='field_of_study',
        ),
    ]
