# Generated by Django 4.2.2 on 2023-06-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_fiel_of_study_student_field_of_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='field_of_study',
            new_name='Field_of_study',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gpa',
            new_name='GPA',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_number',
            new_name='Student_No',
        ),
    ]
